breakouts/mississippi/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "static_pages#home"

  resources :products, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:create, :edit, :update, :destroy]
  end
end

breakouts/mississippi/app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, numericality: true

  has_many :reviews
end

breakouts/mississippi/app/models/review.rb
class Review < ApplicationRecord
  validates :message, presence: true
  validates :message, length: { minimum: 30 }

  belongs_to :product
end

breakouts/mississippi/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products_array = Product.all

    render :index
  end

  def new
    @the_product = Product.new

    render :new
  end


  def create
    the_product = Product.new(product_params)

    if the_product.save
      redirect_to products_path
    else
      @the_product = the_product

      render :new
    end
  end


  def show
    @the_product = Product.find(params[:id])
    @the_review = Review.new

    render :show
  end



  private

  def product_params
    params.require(:product).permit(:name, :price, :image, :description)
  end
end

breakouts/mississippi/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    the_product = Product.find(params[:product_id])
    the_review = the_product.reviews.new(review_params)

    if the_review.save
      redirect_to product_path(the_product)
    else
      @the_product = the_product
      @the_review = the_review

      render "products/show"
    end
  end


  def edit
    @the_product = Product.find(params[:product_id])
    @the_review = @the_product.reviews.find(params[:id])

    render :edit
  end

  def update
    the_product = Product.find(params[:product_id])
    the_review = the_product.reviews.find(params[:id])

    if the_review.update(review_params)
      redirect_to product_path(the_product)
    else
      @the_product = the_product
      @the_review = the_review

      render :edit
    end
  end


  def destroy
    the_product = Product.find(params[:product_id])
    the_review = the_product.reviews.find(params[:id])

    the_review.destroy

    redirect_to product_path(the_product)
  end



  private

  def review_params
    params.require(:review).permit(:message)
  end

end

breakouts/mississippi/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    render :home
  end
end

breakouts/mississippi/app/helpers/products_helper.rb
module ProductsHelper
end

breakouts/mississippi/app/helpers/reviews_helper.rb
module ReviewsHelper
end

breakouts/mississippi/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

breakouts/mississippi/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mississippi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1> Mssss-pp </h1>
    </header>

    <%= yield %>

    <footer>
      <p> Made with &hearts; at Ironhack. </p>
    </footer>
  </body>
</html>

breakouts/mississippi/app/views/products/index.html.erb
<h2> List of products </h2>

<ul>
  <% @products_array.each do |the_product| %>
    <li>
      <%= link_to the_product.name, product_path(the_product) %>

      - $<%= the_product.price %>
    </li>
  <% end %>
</ul>

<%= link_to "Submit a new product", new_product_path %>

breakouts/mississippi/app/views/products/new.html.erb
<h2> Submit a new product </h2>


<% if @the_product.errors.any? %>
  <ul>
    <% @the_product.errors.full_messages.each do |error_message| %>
      <li> <%= error_message %> </li>
    <% end %>
  </ul>
<% end %>


<%= form_for @the_product do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div>
    <%= f.label :image %>
    <%= f.url_field :image %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <%= f.button %>
<% end %>

breakouts/mississippi/app/views/products/show.html.erb
<h2> Product details page </h2>

<h3> <%= @the_product.name %> </h3>

<div> Price: $<%= @the_product.price %> </div>

<p> <%= @the_product.description %> </p>

<img src="<%= @the_product.image %>">


<h4> Reviews </h4>

<ul>
  <% @the_product.reviews.each do |the_review| %>
    <li>
      <%= the_review.message %>
      <%= link_to "Edit", edit_product_review_path(@the_product, the_review) %>

      <%= link_to "Delete", product_review_path(@the_product, the_review), method: "delete", data: { confirm: "Are you sure you want to delete \"#{the_review.message}\"?" } %>
    </li>
  <% end %>
</ul>


<h4> Add a review </h4>

<%= render "reviews/review_form" %>